### ISSUE TITLE
Falta el archivo package.json

### ISSUE THREAD

**Issue by franciscocobas** [ignacio12091/animusica#2]
Hola, estuve viendo el repositorio y tienen el archivo `package-lock.json` pero no el archivo `package.json` que es el importante. 

Por ahora eso, cualquier cosa que vea les comento.

**Comment by ignacio12091** [comment]
Buenas Francisco, master no está actualizado, la rama que hicimos para que corrijan es "entregable". Igualmente gracias por el comentario, cualquier duda a las órdenes.
